name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413

      - uses: actions/setup-node@v7
        with:
          node-version: "24"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm run test
      - run: pnpm run typecheck
      - run: pnpm run lint
      - run: pnpm run format
